#!/bin/bash

#Colours

RED="\e[1;31m"
GREEN="\e[1;32m"
WHITE="\e[0m"

#Variables

CHROOT_DIR=/data/local/mnt
CONFIG_DIR=~/.chroot_installer
ANDROIDVERSION=$(getprop ro.build.version.release | cut -f1,2 -d '.')
ROOTFS_DIR=~/installed-rootfs
#this for cycle put all arguments into array argslist
index=1
for var in "$@" 
do
	argslist[$index]=$var
	index=$((index+1))
done
#Create a config file with the same name as the container
CONFIG_FILE=$CONFIG_DIR/${argslist[2]}.conf
NOTDEBIAN=false

#function that makes the filesystem image where the rootfs get unpacked

make_image(){

#Ask user questions about the image
    echo -e "\nCreating the rootfs image, requires at least 8GB of storage\n"
    read -p "Select an image name: " IMGNAME
    read -p "Select an installation path: " SPATH
    read -p "Select image size in megabytes: " SIZE

#Keep track of the user input installation path
    INSPATH=$SPATH/$IMGNAME.img
#Calculate size in KB from user input size and use that to calculate dd count
    SIZEKB=$(($SIZE*1000))
    COUNT=$(($SIZEKB/4))
#Write installation path to config file
    echo "INSPATH=$INSPATH" > $CONFIG_FILE

#Unmount any mounted container before making the image
    if findmnt $CHROOT_DIR >/dev/null
    then
        sudo umount -l $CHROOT_DIR
    fi

#Make the image only if it doesn't exist or if its size doesn't match the user input one. It disables some features that may not be supported by some older Android kernels as well.
    if [ ! -f $INSPATH ] || (( "$(du --apparent-size -k $INSPATH | cut -f1)" < $SIZE ))
    then
        sudo dd if=/dev/zero of=$INSPATH bs=4k count=$COUNT
    fi
    sudo mkfs.ext4 $INSPATH
    sudo tune2fs -O ^metadata_csum $INSPATH
    sudo tune2fs -i0 -c0 $INSPATH
#Mount the image
    sudo mount -o loop $INSPATH $CHROOT_DIR
#Based on the extension, we unpack the rootfs into the mounted image
    FILENAME="$(basename $ROOTFS)"
    case "$FILENAME" in
    *.tar.bz2)
              sudo tar --skip-old-files -xjf $ROOTFS -C $CHROOT_DIR
              ;;
    *.tar.gz)
			if [ "${argslist[3]}" == "manjaro" ]
			then
                  sudo bsdtar -k -xpf $ROOTFS -C $CHROOT_DIR
            else
            	  sudo tar --skip-old-files -xzf $ROOTFS -C $CHROOT_DIR
            fi

    esac
    sudo umount -l $CHROOT_DIR
}

#Function to make a rootfs folder in case it has been chosen by user as installation method
make_folder(){

#Create a folder with the same name as the container
  INSPATH=$ROOTFS_DIR/${argslist[2]}
  mkdir -p $INSPATH
#Gives it the right permissions
  sudo chmod 755 $INSPATH
  sudo chown 0:0 $INSPATH
  FILENAME="$(basename $ROOTFS)"
  case "$FILENAME" in
  *.tar.bz2)
  	sudo tar --skip-old-files -xjf $ROOTFS -C $INSPATH
  	;;
  *.tar.gz)
    if [ "${argslist[3]}" == "manjaro" ]
    then
        sudo bsdtar -k -xpf $ROOTFS -C $INSPATH
    else
      	sudo tar --skip-old-files -xzf $ROOTFS -C $INSPATH
    fi
    esac
  echo "INSPATH=$INSPATH" > $CONFIG_FILE
	
}

#Function that makes the last created container the default one
mark_default(){

for i in $CONFIG_DIR/* #check each file for default flag and remove it
do
    if [ "$(tail -n 1 $i)" == "default" ]
    then
        sed -i '$ d' $i
    fi
done

echo "default" >> $CONFIG_FILE




	
}

#Function that does some preliminary setups on the chroot
first_setup(){

echo -e "\nPreparing the chroot. This process will involve creating an user account, adding important Android groups, installing some required packages, importing some installation scripts and appending a bunch of variables to env. If it hangs for a few minutes, please wait"

#check the chroot package manager and save it to variable
if ls $CHROOT_DIR/usr/bin | grep -wq "apt$" 
then 
	PACKAGEMANAGER=apt
else
	PACKAGEMANAGER=pacman
fi 

#Check that the user didn't select a custom rootfs and in case write the installed distro in the config file
if [ ! "${argslist[3]}" == "--custom" ]
then
  echo "DISTRO=${argslist[3]}" >> $CONFIG_FILE
fi
#Ask the user to create an username then write it in the config file

  echo -e "\n"
  read -p "Input an username: " USRNAME
  echo "USERNAME=$USRNAME" >> $CONFIG_FILE
  mark_default
#Copy hostname and hosts in the chroot
  sudo cp $PREFIX/etc/resolv.conf $CHROOT_DIR/etc
  sudo cp setup/hosts $CHROOT_DIR/etc
#Additional setup required for Manjaro
  if [ "$PACKAGEMANAGER" == "pacman" ]
  then
#Copy custom pacman.conf to chroot with disabled signature checking
      sudo cp setup/pacman.conf $CHROOT_DIR/etc
      su -c busybox chroot $CHROOT_DIR "/usr/bin/pacman-key --init >/dev/null 2>&1"
      su -c busybox chroot $CHROOT_DIR "/usr/bin/pacman-key --populate archlinux-arm manjaro-arm manjaro >/dev/null 2>&1"
      su -c busybox chroot $CHROOT_DIR "/usr/bin/pacman-mirrors -f10 >/dev/null 2>&1"
      su -c busybox chroot $CHROOT_DIR "/usr/bin/pacman -Syyu base manjaro-system manjaro-release --noconfirm >/dev/null 2>&1"
      su -c busybox chroot $CHROOT_DIR "/usr/sbin/groupadd wheel >/dev/null 2>&1"
      su -c busybox chroot $CHROOT_DIR "/usr/sbin/useradd --create-home $USRNAME >/dev/null 2>&1"
      su -c busybox chroot $CHROOT_DIR "/usr/sbin/usermod -aG wheel $USRNAME >/dev/null 2>&1"
      
  fi    
#Set right permissions for hosts	
  sudo chown 0:0 $CHROOT_DIR/etc/hosts
  sudo chmod 644 $CHROOT_DIR/etc/hosts
#Create a password for the user account, the root account, create Android specific groups
  su -c busybox chroot /data/local/mnt "/usr/bin/echo 'localhost' > $CHROOT_DIR/etc/hostname"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/useradd --create-home $USRNAME >/dev/null 2>&1"
  echo -e "\nUser account created, please insert a password for it: "
  su -c busybox chroot $CHROOT_DIR "/usr/bin/passwd $USRNAME"
  echo -e "\nPassword registered, please insert one for your root account as well: "
  su -c busybox chroot $CHROOT_DIR "/usr/bin/passwd root"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/groupadd -g 3001 aid_net_bt_admin >/dev/null 2>&1"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/groupadd -g 3002 aid_net_bt >/dev/null 2>&1"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/groupadd -g 3003 aid_inet >/dev/null 2>&1"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/groupadd -g 3004 aid_net_raw >/dev/null 2>&1"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/groupadd -g 3005 aid_net_admin >/dev/null 2>&1"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/usermod -aG aid_inet,aid_net_raw,aid_net_admin,aid_net_bt,aid_net_bt_admin $USRNAME >/dev/null 2>&1"
  su -c busybox chroot $CHROOT_DIR "/usr/sbin/usermod -aG aid_inet,aid_net_raw,aid_net_admin,aid_net_bt,aid_net_bt_admin root >/dev/null 2>&1"

  
  #Install some required packages
  if [ "$PACKAGEMANAGER" == "apt" ]
  then
  		su -c busybox chroot $CHROOT_DIR "/usr/sbin/usermod -g 3003 _apt"
		su -c busybox chroot $CHROOT_DIR '/bin/su - root -c "apt update"'
		su -c busybox chroot $CHROOT_DIR '/bin/su - root -c "apt install sudo wget gnupg2 xwayland -y"'
		su -c busybox chroot $CHROOT_DIR "/usr/sbin/usermod -aG sudo $USRNAME"             
  elif [ "$PACKAGEMANAGER" == "pacman" ]
  then
		NOTDEBIAN=true
		su -c busybox chroot $CHROOT_DIR '/bin/su - root -c "pacman -Syu --noconfirm"'
        su -c busybox chroot $CHROOT_DIR '/bin/su - root -c "pacman -S --noconfirm sudo wget gnupg"'

  fi

  echo -e "\nFirst setup almost completed, setting up the chroot env"
  
  sudo mkdir -p $CHROOT_DIR/home/$USRNAME/scripts
  sudo cp setup/*.sh $CHROOT_DIR/home/$USRNAME/scripts
  sudo chmod -R a+rwx $CHROOT_DIR/home/$USRNAME/scripts

  
  #Append important env variables to /etc/profile and also modify the main shell to bash                      
  su -c busybox chroot $CHROOT_DIR  /usr/bin/sudo -u $USRNAME -i "bash -c /home/$USRNAME/scripts/setup_env.sh"



}

install_de(){

read -p "Select a DE among the available choices[xfce|lxqt|icewm|fluxbox]: " DE
#check which DE has been chosen and install dependencies based on distro
if [ "$DE" == "xfce" ]
then
	if [ "$PACKAGEMANAGER" == "apt" ]
	then
		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "apt install tigervnc-standalone-server tigervnc-common dbus-x11 tigervnc-xorg-extension xfce4 xfce4-goodies -y"
	elif [ "$PACKAGEMANAGER" == "pacman" ]
	then
		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "pacman -S --noconfirm tigervnc dbus xfce4 xfce4-goodies"
	fi
elif [ "$DE" == "lxqt" ]
then
	if [ "$PACKAGEMANAGER" == "apt" ]
	then
		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "apt install tigervnc-standalone-server tigervnc-common dbus-x11 tigervnc-xorg-extension lxqt -y"
	elif [ "$PACKAGEMANAGER" == "pacman" ]
	then
		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "pacman -S --noconfirm tigervnc dbus lxqt"
	fi
elif [ "$DE" == "icewm" ]
then
	if [ "$PACKAGEMANAGER" == "apt" ]
	then
		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "apt install tigervnc-standalone-server tigervnc-common dbus-x11 tigervnc-xorg-extension icewm -y"
	elif [ "$PACKAGEMANAGER" == "pacman" ]
	then
		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "pacman -S --noconfirm tigervnc dbus icewm"
	fi
elif [ "$DE" == "fluxbox" ]
then
	 if [ "$PACKAGEMANAGER" == "apt" ]
	 then
	      su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "apt install tigervnc-standalone-server tigervnc-common dbus-x11 tigervnc-xorg-extension fluxbox xterm -y"
	  elif [ "$PACKAGEMANAGER" == "pacman" ]
	  then
	      su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "pacman -S --noconfirm tigervnc dbus fluxbox xterm"
	fi
fi

	
su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u $USRNAME -i "bash -c /home/$USRNAME/scripts/install_vnc.sh"	
	
}

install(){

echo -e "$RED""\nWARNING: THIS SCRIPT IS UNTESTED ON ANDROID VERSIONS NEWER THAN 10, SO IT MAY NOT WORK. ISSUES ABOUT NOT WORKING ON NEWER ANDROID VERSIONS WILL ONLY BE ACCEPTED WHEN PROPER LOGS ARE PROVIDED""$WHITE"
echo -e "$RED""\nWARNING: TERMUX:X11 APP MAY NOT WORK IN A CHROOT DEPENDING ON YOUR ANDROID VERSION. NO ISSUES WILL BE ACCEPTED ABOUT TERMUX:X11 AS THEY AREN'T RELATED TO THIS SCRIPT""$WHITE"
sleep 4
clear


echo    "**********************************************"
echo    "#                                            #"
echo -e "#           $RED CHROOT-INSTALLER v0.1$WHITE           #"
echo    "#                                            #"
echo    "**********************************************"

#check if the container is valid and in case ask if the user wants to recreate it
if [ -f $CONFIG_FILE ]
then
    USERNAME=$(cat $CONFIG_FILE | awk -F '='  '/USERNAME/{print $2}')
    INSPATH=$(cat $CONFIG_FILE | awk -F '=' '/INSPATH/{print $2}')
    if [ "$USERNAME" == "" ] || [ "$INSPATH" == "" ]
    then
        echo -e "This container seems to exist but it looks empty, so I will recreate it"
    else
        read -p "This container already exists, do you want me to recreate it [y|n]: " CHOICE
        if [ "$CHOICE" == "n" ]
        then
        	echo -e "\nI will leave then"
        	exit
        fi
    fi
fi

#based on options and arguments, set the right rootfs variable
if [ "${argslist[3]}" == "--custom" ]
then
	echo -e "\nUsing user selected rootfs"
	ROOTFS=${argslist[4]}
elif [ "${argslist[3]}" == "debian" ]
then
	echo -e "\nDownloading debian rootfs"
	if [ ! -f /sdcard/debian.tar.bz2 ]
	then
		megadl https://mega.nz/file/cV5ClJrb#h5UvcIdiLq2zFncGYBe3lBL3QjauJFmLupu2faKvFUY --path=/sdcard
	fi
	ROOTFS=/sdcard/debian.tar.bz2
elif [ "${argslist[3]}" == "ubuntu" ]
then
	if [ ! -f /sdcard/ubuntu-base-22.04.1-base-arm64.tar.gz ]
	then
		wget http://cdimage.ubuntu.com/ubuntu-base/releases/jammy/release/ubuntu-base-22.04.1-base-arm64.tar.gz -P /sdcard
	fi
	ROOTFS=/sdcard/ubuntu-base-22.04.1-base-arm64.tar.gz
elif [ "${argslist[3]}" == "manjaro" ]
then
	if [ ! -f /sdcard/Manjaro-ARM-aarch64-latest.tar.gz ]
    then
         wget https://github.com/manjaro-arm/rootfs/releases/download/20230220/Manjaro-ARM-aarch64-latest.tar.gz -P /sdcard
    fi
    ROOTFS=/sdcard/Manjaro-ARM-aarch64-latest.tar.gz
else
	echo -e "No valid distro or rootfs specified, exiting"
	exit
fi


echo -e "\nInitialization installation of the rootfs\n"


sudo mkdir -p $CHROOT_DIR
sudo chown 755 $CHROOT_DIR
mkdir -p $CONFIG_DIR
touch $CONFIG_FILE
read -p "Select an installation method: " INSMETHOD


if [ "$INSMETHOD" == "file" ]
then
	make_image

else
	
	make_folder
fi

echo -e "\nMounting the container"

if findmnt $CHROOT_DIR >/dev/null
then
	sudo umount -l $CHROOT_DIR
fi
#verify installation method then mount it based on it
if [ "$INSMETHOD" == "file" ] 
then
	sudo mount -o loop $INSPATH $CHROOT_DIR
else
#for folder method mount bind it in another directory so we can remount it with proper permissions
	sudo mount --bind $INSPATH $CHROOT_DIR
	sudo mount -o remount,bind,suid,exec $CHROOT_DIR
fi 
for i in dev proc sys dev/pts dev/tty
do
	sudo busybox mount --bind /$i $CHROOT_DIR/$i
done

first_setup

#check if -d option is present
for i in ${argslist[@]}
do
  if [ "$i" == "-d" ]
  then
  		echo -e "\nInstalling a DE\n"
		install_de
	fi
done
#check if -b option is present
 for i in ${argslist[@]}
 do
	if [ "$i" == "-b" ]  &&	[ "$NOTDEBIAN" == "false" ]
  	then
        echo -e "\nInstalling wine,box86,box64\n"
        su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u $USRNAME -i "bash -c /home/$USRNAME/scripts/install_box.sh"
		#check if kernel has binfmt_misc support and in case install right dependencies 
		  if [ -d /proc/sys/fs/binfmt_misc ]
		  then
          		sudo busybox mount --bind /proc/sys/fs/binfmt_misc $CHROOT_DIR/proc/sys/fs/binfmt_misc
          		echo -e "\nInstalling binfmt entries"
          		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "apt install binfmt-support -y"
          		sudo cp binfmt-confs/box86 binfmt-confs/box64  $CHROOT_DIR/usr/share/binfmts
          		su -c busybox chroot $CHROOT_DIR /usr/bin/sudo -u root -i "update-binfmts --import"
          fi

	 fi
  done


echo -e "\nFirst setup completed, stopping the chroot"

sudo umount -l $CHROOT_DIR

echo -e "\nCopying the chroot-launcher and chroot-installer scripts to $PATH"

cp setup/chroot-launcher $PATH
cp chroot-installer $PATH
chmod +x $PATH/chroot-launcher $PATH/chroot-installer

}

remove(){

index=1
#get and check all arguments after remove
for i in ${argslist[@]}
do
	if (( index>1 ))
	then
		CONFIG_FILE=$CONFIG_DIR/$i.conf
		if [ -f $CONFIG_FILE ]
		then
			INSPATH=$(cat $CONFIG_FILE | awk -F '=' '/INSPATH/{print $2}')
			echo -e "Unmounting any running container"
			sudo umount -l $CHROOT_DIR >/dev/null 2>&1
			sudo umount -l $CHROOT_DIR/media/* 2>&1
			echo -e "Deleting the selected container"
			sudo rm -rf $INSPATH
			sudo rm -rf $CONFIG_FILE
		else
			printf "The container %s doesn't exist, please specify a valid container\n" "$i"
		fi
	fi
	index=$((index+1))
done
	
}

list (){

#default status is not installed
debianstatus="$RED""NotInstalled""$WHITE"
manjarostatus="$RED""NotInstalled""$WHITE"
ubuntustatus="$RED""NotInstalled""$WHITE"

index=1
#check all configs and save installed distros paramaters in an array
for conf in $CONFIG_DIR/*
do
	distro="$(cat $conf | gawk -F "=" '/DISTRO/{print $2}')"
	installedistros[$index]="$distro"
	index=$((index+1))
done

#if a distro is installed change status
for dist in ${installedistros[@]}
do
	case "$dist" in
	debian)
			debianstatus="$GREEN""Installed""$WHITE"
			;;
	ubuntu)
			ubuntustatus="$GREEN""Installed""$WHITE"
			;;
	manjaro)
			manjarostatus="$GREEN""Installed""$WHITE"
	esac
done
			
			

printf "\n%-s%19s\n" "Available distros:" "Status:"
echo -e "\nDebian 11 Bullseye            $debianstatus"
echo -e "Ubuntu 22.04 JammyFish        $ubuntustatus"
echo -e "Manjaro ARM                   $manjarostatus"

}

#Waiting for public release to update it
update(){

#git clone 
chmod +x chroot-installer
mv chroot-installer $PATH
	
}


#version function that simply prints version number

version(){

echo -e "chroot-installer v0.1"
	
}

#help function
help(){


column1=(
"install" 
"remove" 
"list" 
"update" 
"help" 
"--custom" 
"-d" 
"-b" 
"--version")
column2=(
"install distro specified by distro argument in container containername" 
"remove the container specified by argument containername alongside all of its files" 
"list available distros and their installation status" 
"update this script then exit" 
"print this help message then exit" 
"can be specified alongside install and in place of argument distro for inputting custom rootfses through the argument path, only debian-based rootfses are guaranteed to work" 
"install a desktop environment of your choice alongside VNC, disabled by default" 
"install box86 and box64 alongside wine to run x86 apps,disabled by default and only available for debian-based distros"
"print this script version then exit"
)
argcolumn1=("containername" "path" "distro")
argcolumn2=("arbitrary container name of user's choice" "full path to the custom rootfs, to use only with --custom option" "name of the distro to install" )

echo -e "chroot-installer: chroot-installer [install|remove|update|list|help|--version] containername distro|[--custom] path [-b,-d]"
echo -e "\nScript thath help to install and remove chroot containers for rooted device with busybox installed.\n"
echo -e "\nOptions:\n"
paste <(printf "%-20s\n" "${column1[@]}") <(printf "%-20s\n" "${column2[@]}")
echo -e "\nArguments:\n"
paste <(printf "%-20s\n" "${argcolumn1[@]}") <(printf "%20s\n" "${argcolumn2[@]}")

}

if [[ "$(su -c busybox)" =~ "not found" ]]
then
    echo "Busybox not available,please install busybox before using this installer"
    exit 0
fi

if (( $(echo "$ANDROIDVERSION>12" | bc -l) ))
then
    if [ "$(su -c settings get global settings_enable_monitor_phantom_procs)" == "true" ]
    then
        echo -e "Android 12.1 or greater detected, disabling phantom processes killer"
        su -c settings put global settings_enable_monitor_phantom_procs false
    fi
fi

while [ True ]
do
	if [ "${argslist[1]}" == "install" ]
	then
		install
		break
	elif [ "${argslist[1]}" == "remove" ]
	then
		remove
		break
	elif [ "${argslist[1]}" == "update" ]
	then
		update
		break
	elif [ "${argslist[1]}" == "list" ]
	then
		list
		break
	elif [ "${argslist[1]}" == "help" ]
	then
		help
		break
	elif [ "${argslist[1]}" == "--version" ]
	then
		version
		break
	else
		help
		break
	fi
done

