#!/bin/bash

cd ~
wget https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton7-42/wine-lutris-GE-Proton7-42-x86_64.tar.xz 
tar -xf wine-lutris-GE-Proton7-42-x86_64.tar.xz
rm -rf wine-lutris-GE-Proton7-42-x86_64.tar.xz

